
### Register a new user
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
    "username": "testuserforpasswordreseta",
    "email": "vojtechtlamka@gmail.com",
    "password": "testpassword123"
}

### Login and obtain a token
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "Nikca",
    "password": "ahoj"
}

### Request password reset
POST http://localhost:8000/api/auth/password-reset/
Content-Type: application/json

{
    "email": "vojtechtlamka@gmail.com"
}

### Confirm password reset (replace <uid> and <token> with actual values from email)
POST http://localhost:8000/api/auth/password-reset-confirm/1/some-token/
Content-Type: application/json

{
    "password": "newtestpassword123"
}

### Create a new note (replace <your_token> with your auth token)
POST http://localhost:8000/api/notes/
Authorization: Token 5e7497d176ddd0897168c4c7aea519d4f909ac0e
Content-Type: application/json

{
    "title": "Sample Note2",
    "body": "This is a sample note2.",
    "due_date": "2025-05-01T12:00:00Z",
    "priority": "Low",
    "category": "Personal"
}

### List all notes
GET http://localhost:8000/api/notes/
Authorization: Token 5e7497d176ddd0897168c4c7aea519d4f909ac0e

### Retrieve a single note (replace <note_id> with the actual note ID)
GET http://localhost:8000/api/notes/1/
Authorization: Token ce96b3be7fe399826494631ea0f029ed5e794e4e

### Update a note (replace <note_id> with the actual note ID)
PUT http://localhost:8000/api/notes/12/
Authorization: Token 5e7497d176ddd0897168c4c7aea519d4f909ac0e
Content-Type: application/json

{
    "id": 12,
    "title": "Hey",
    "body": "hey",
    "due_date": "2025-04-30T15:47:00Z",
    "priority": 1,
    "category": "Other"
}

### Delete a note (replace <note_id> with the actual note ID)
DELETE http://localhost:8000/api/notes/2/
Authorization: Token ce96b3be7fe399826494631ea0f029ed5e794e4e

###

PATCH http://localhost:8000/api/notes/8/ HTTP/1.1
Authorization: Token dda4fce18dd2dd206077362a5cfbbfa955993c0c
Content-Type: application/json

{
  "priority": 1
}